{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "2f1f79ab",
   "metadata": {},
   "outputs": [],
   "source": [
    "import import_ipynb"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "b994500d",
   "metadata": {},
   "outputs": [],
   "source": [
    "import telegram"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "5d5abcd3",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "# hermes_token = '5035520069:AAHXrviXBFO9didF_6HEpE1WhBeLuw-rTUM'\n",
    "# hermes = telegram.Bot(token = hermes_token)\n",
    "# updates = hermes.getUpdates()\n",
    "# for u in updates:\n",
    "#     print(u.message)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "d3602e15",
   "metadata": {},
   "outputs": [],
   "source": [
    "# my_token = '5035520069:AAHXrviXBFO9didF_6HEpE1WhBeLuw-rTUM' #토큰을 설정해 줍니다.\n",
    "\n",
    "# bot = telegram.Bot(token = my_token) #봇을 생성합니다.\n",
    "\n",
    "# bot.sendMessage(chat_id='@hermes_test', text=\"I'm bot\") #@bill_chat 으로 메세지를 보냅니다.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "52870bfe",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "start telegram chat bot\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/var/folders/v3/66kqwghs2875w1qzljpsmkmw0000gn/T/ipykernel_21830/2856060335.py:83: TelegramDeprecationWarning: The argument `clean` of `start_polling` is deprecated. Please use `drop_pending_updates` instead.\n",
      "  updater.start_polling(timeout=30, clean=True)\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/loop.py\", line 58, in run_forever\n",
      "    result = self._bot.getUpdates(offset=offset,\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/bot.py\", line 2945, in get_updates\n",
      "    self._post(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/utils/request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/utils/request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/loop.py\", line 58, in run_forever\n",
      "    result = self._bot.getUpdates(offset=offset,\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/bot.py\", line 2945, in get_updates\n",
      "    self._post(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/utils/request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/utils/request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/loop.py\", line 58, in run_forever\n",
      "    result = self._bot.getUpdates(offset=offset,\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/bot.py\", line 2945, in get_updates\n",
      "    self._post(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/utils/request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/utils/request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/loop.py\", line 58, in run_forever\n",
      "    result = self._bot.getUpdates(offset=offset,\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/bot.py\", line 2945, in get_updates\n",
      "    self._post(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/utils/request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/utils/request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/loop.py\", line 58, in run_forever\n",
      "    result = self._bot.getUpdates(offset=offset,\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/bot.py\", line 2945, in get_updates\n",
      "    self._post(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/utils/request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/utils/request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/loop.py\", line 58, in run_forever\n",
      "    result = self._bot.getUpdates(offset=offset,\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/bot.py\", line 2945, in get_updates\n",
      "    self._post(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/utils/request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/utils/request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/loop.py\", line 58, in run_forever\n",
      "    result = self._bot.getUpdates(offset=offset,\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/bot.py\", line 2945, in get_updates\n",
      "    self._post(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/utils/request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/utils/request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/loop.py\", line 58, in run_forever\n",
      "    result = self._bot.getUpdates(offset=offset,\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/bot.py\", line 2945, in get_updates\n",
      "    self._post(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/utils/request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/utils/request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/loop.py\", line 58, in run_forever\n",
      "    result = self._bot.getUpdates(offset=offset,\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/bot.py\", line 2945, in get_updates\n",
      "    self._post(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/utils/request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/utils/request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/loop.py\", line 58, in run_forever\n",
      "    result = self._bot.getUpdates(offset=offset,\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n",
      "Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py\", line 646, in _network_loop_retry\n",
      "    if not action_cb():\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/updater.py\", line 597, in polling_action_cb\n",
      "    updates = self.bot.get_updates(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/extbot.py\", line 222, in get_updates\n",
      "    updates = super().get_updates(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/bot.py\", line 130, in decorator\n",
      "    result = func(*args, **kwargs)\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/bot.py\", line 2945, in get_updates\n",
      "    self._post(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/bot.py\", line 295, in _post\n",
      "    return self.request.post(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/utils/request.py\", line 361, in post\n",
      "    result = self._request_wrapper(\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/utils/request.py\", line 283, in _request_wrapper\n",
      "    raise Conflict(message)\n",
      "telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/loop.py\", line 58, in run_forever\n",
      "    result = self._bot.getUpdates(offset=offset,\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/__init__.py\", line 1000, in getUpdates\n",
      "    return self._api_request('getUpdates', _rectify(p))\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/__init__.py\", line 491, in _api_request\n",
      "    return api.request((self._token, method, params, files), **kwargs)\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/api.py\", line 155, in request\n",
      "    return _parse(r)\n",
      "  File \"/usr/local/Cellar/jupyterlab/3.2.4/libexec/lib/python3.9/site-packages/telepot/api.py\", line 150, in _parse\n",
      "    raise exception.TelegramError(description, error_code, data)\n",
      "telepot.exception.TelegramError: ('Conflict: terminated by other getUpdates request; make sure that only one bot instance is running', 409, {'ok': False, 'error_code': 409, 'description': 'Conflict: terminated by other getUpdates request; make sure that only one bot instance is running'})\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "import telepot\n",
    "from telepot.loop import MessageLoop\n",
    "from telepot.namedtuple import InlineKeyboardMarkup as MU # 마크업\n",
    "from telepot.namedtuple import InlineKeyboardButton as BT # 버튼\n",
    "from telegram.ext import Updater, MessageHandler, Filters, CommandHandler\n",
    "\n",
    "token = '5035520069:AAHXrviXBFO9didF_6HEpE1WhBeLuw-rTUM'\n",
    "chat_id = '@hermes_test'\n",
    "bot = telepot.Bot(token)\n",
    "\n",
    "updater = Updater(token=token, use_context=True) \n",
    "dispatcher = updater.dispatcher \n",
    "\n",
    "# Welcome a user to the chat\n",
    "def welcome(update, context, new_member):\n",
    "    \"\"\" Welcomes a user to the chat \"\"\"\n",
    "\n",
    "    message = update.message\n",
    "    chat_id = message.chat.id\n",
    "    logger.info(\n",
    "        \"%s joined to chat %d (%s)\",\n",
    "        escape(new_member.first_name),\n",
    "        chat_id,\n",
    "        escape(message.chat.title),\n",
    "    )\n",
    "\n",
    "    # Pull the custom message for this chat from the database\n",
    "    text = db.get(str(chat_id))\n",
    "\n",
    "    # Use default message if there's no custom one set\n",
    "    if text is None:\n",
    "        text = \"Hello $username! Welcome to $title 😊\"\n",
    "\n",
    "    # Replace placeholders and send message\n",
    "    text = text.replace(\"$username\", new_member.first_name)\n",
    "    text = text.replace(\"$title\", message.chat.title)\n",
    "    send_async(context, chat_id=chat_id, text=text, parse_mode=ParseMode.HTML)\n",
    "\n",
    "def action(msg):\n",
    "    if msg['text'] == \"link\":\n",
    "        btn1 = BT(text = \"Website\", url = \"https://xd.adobe.com/view/2314682e-3f11-491b-9c1e-1fe804a3e242-7647/\", callback_data = \"1\")\n",
    "        btn2 = BT(text = \"Twitter\", url = \"https://twitter.com/official_LUCK_\", callback_data = \"2\")\n",
    "        btn3 = BT(text = \"Reddit\", url = \"https://www.reddit.com/user/official_LUCK_\", callback_data = \"3\")\n",
    "        mu = MU(inline_keyboard = [[btn1], [btn2], [btn3]])\n",
    "        bot.sendMessage(chat_id, \"Choose one\", reply_markup = mu)\n",
    "    elif msg['text'] == 'start':\n",
    "        bot.sendMessage(chat_id, \"Get $LUCK & Getting Lucky!\")\n",
    "\n",
    "def query_ans(msg):\n",
    "    query_id = msg[\"id\"]\n",
    "    query_data = msg[\"data\"]\n",
    "    if query_data == \"1\":\n",
    "        bot.answerCallbackQuery(query_id, text = \"Website\")\n",
    "    elif query_data == \"2\":\n",
    "        bot.answerCallbackQuery(query_id, text = \"Twitter\")\n",
    "    elif query_data == \"3\":\n",
    "        bot.answerCallbackQuery(query_id, text = \"Reddit\")\n",
    "        \n",
    "\n",
    "print('start telegram chat bot')\n",
    "\n",
    "MessageLoop(bot, {'chat' : action, 'callback_query' : query_ans}).run_as_thread()\n",
    "\n",
    "def empty_message(update, context):\n",
    "    \"\"\"\n",
    "    Empty messages could be status messages, so we check them if there is a new\n",
    "    group member, someone left the chat or if the bot has been added somewhere.\n",
    "    \"\"\"\n",
    "\n",
    "    if update.message.new_chat_members:\n",
    "        for new_member in update.message.new_chat_members:\n",
    "            # Bot was added to a group chat\n",
    "            if new_member.username == BOTNAME:\n",
    "                return introduce(update, context)\n",
    "            # Another user joined the chat\n",
    "            else:\n",
    "                return welcome(update, context, new_member)\n",
    "\n",
    "\n",
    "dispatcher.add_handler(MessageHandler(Filters.status_update, empty_message))\n",
    "# dispatcher.add_error_handler(error)\n",
    "updater.start_polling(timeout=30, clean=True)\n",
    "updater.idle()\n",
    "\n",
    "# updater.start_polling()\n",
    "# updater.idle()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "8e871dc3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "start telegram chat bot\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/var/folders/v3/66kqwghs2875w1qzljpsmkmw0000gn/T/ipykernel_8974/544104263.py:27: TelegramDeprecationWarning: The argument `clean` of `start_polling` is deprecated. Please use `drop_pending_updates` instead.\n",
      "  updater.start_polling(timeout=3, clean=True)\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/dispatcher.py\", line 555, in process_update\n",
      "    handler.handle_update(update, self, check, context)\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/handler.py\", line 198, in handle_update\n",
      "    return self.callback(update, context)\n",
      "  File \"/var/folders/v3/66kqwghs2875w1qzljpsmkmw0000gn/T/ipykernel_8974/544104263.py\", line 10, in get_message\n",
      "    update.message.reply_text(\"got text\")\n",
      "AttributeError: 'NoneType' object has no attribute 'reply_text'\n",
      "No error handlers are registered, logging exception.\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/dispatcher.py\", line 555, in process_update\n",
      "    handler.handle_update(update, self, check, context)\n",
      "  File \"/usr/local/lib/python3.9/site-packages/telegram/ext/handler.py\", line 198, in handle_update\n",
      "    return self.callback(update, context)\n",
      "  File \"/var/folders/v3/66kqwghs2875w1qzljpsmkmw0000gn/T/ipykernel_8974/544104263.py\", line 10, in get_message\n",
      "    update.message.reply_text(\"got text\")\n",
      "AttributeError: 'NoneType' object has no attribute 'reply_text'\n"
     ]
    }
   ],
   "source": [
    "from telegram.ext import Updater, MessageHandler, Filters, CommandHandler  # import modules\n",
    "\n",
    "my_token = '5035520069:AAHXrviXBFO9didF_6HEpE1WhBeLuw-rTUM'\n",
    "\n",
    "print('start telegram chat bot')\n",
    "\n",
    "\n",
    "# message reply function\n",
    "def get_message(update, context) :\n",
    "    update.message.reply_text(\"got text\")\n",
    "    update.message.reply_text(update.message.text)\n",
    "\n",
    "\n",
    "# help reply function\n",
    "def help_command(update, context) :\n",
    "    update.message.reply_text(\"무엇을 도와드릴까요?\")\n",
    "\n",
    "\n",
    "updater = Updater(my_token, use_context=True)\n",
    "\n",
    "message_handler = MessageHandler(Filters.text & (~Filters.command), get_message) # 메세지중에서 command 제외\n",
    "updater.dispatcher.add_handler(message_handler)\n",
    "\n",
    "help_handler = CommandHandler('help', help_command)\n",
    "updater.dispatcher.add_handler(help_handler)\n",
    "\n",
    "updater.start_polling(timeout=3, clean=True)\n",
    "updater.idle()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "02a8fd7e",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "import ChatBotModel\n",
    "\n",
    "def greeting(bot, update):\n",
    "    hermes.sendMessage('Welcome,')\n",
    "    sound = naming()\n",
    "    hermes.sendMessage(sound)\n",
    "    hermes.sendMessage('!!')\n",
    "\n",
    "def goodbye(bot, update):\n",
    "    hermes.sendMessage('Good Bye!')\n",
    "#     hermes.stop()\n",
    "\n",
    "def naming():\n",
    "    return 'Loop!'\n",
    "\n",
    "hermes = ChatBotModel.BotHermes()\n",
    "hermes.add_handler('greeting', greeting)\n",
    "hermes.add_handler('stop', goodbye)\n",
    "hermes.start()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6240823b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
